name: Scorecard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scorecard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Scorecard
      uses: ossf/scorecard-action@v2  # Updated to use v2 instead of v2.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

