name: Scorecard

on:
  push:
    branches:
      - gh-pages  # Update to match your default branch
  pull_request:
    branches:
      - gh-pages

jobs:
  scorecard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Scorecard
      uses: ossf/scorecard-action@v2.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

